import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Moon,Sun,Terminal,ArrowDown,ExternalLink,Code2,Database,Workflow,ScanLine,ChevronRight}from'lucide-react';
import'./style.css';

const skills=['PYTHON','JAVASCRIPT','REACT','CLOUDFLARE','REST APIs','APPS SCRIPT','EXCEL','GOOGLE SHEETS','OCR','COMPUTER VISION','GIT/GITHUB','WEBGPU'];
const projects=[
 ['01','DAM OPERATIONS','Multi-branch operations platform','React • Cloudflare Workers • REST APIs • Google Sheets','Staff-facing operational workflows, inventory logic, validation, duplicate protection, local drafts and backend API architecture.'],
 ['02','OPERATIONS DATA ENGINE','Data automation & reporting','Python • Excel • Google Sheets • Automation','Multi-file stock analysis, consumption reporting, workforce processing, validation and branch-level operational reporting.'],
 ['03','SCHEDULE INTELLIGENCE','Workforce analytics','Python • Parsing • Business Rules • Excel','Parses straight and broken shifts, classifies duties, calculates working hours and overtime, and creates structured workforce analysis.'],
 ['04','DELIVERY NOTE VISION','Document intelligence R&D','OCR • Computer Vision • JavaScript • WebGPU','Experiments for turning photographed delivery notes into structured SKU, product, quantity and UOM data.']
];
function Avatar(){return <div className="avatarWrap"><div className="depthRings"><i/><i/><i/></div><div className="avatar" aria-label="stylized character of Yashwanth"><div className="hair"/><div className="head"><div className="glasses"><i/><i/><b/></div><div className="ear"/></div><div className="neck"/><div className="body"><div className="shirtLine"/></div><div className="arm left"><i/></div><div className="arm right"><i className="forearm"/><b className="hand">›</b></div><div className="leg l"/><div className="leg r"/></div><div className="floorGlow"/></div>}
function App(){const[light,setLight]=useState(false);const[recruiter,setRecruiter]=useState(false);const[stage,setStage]=useState(0);
 useEffect(()=>{let ts=[700,1700,2800,3900,5000];ts.forEach((t,i)=>setTimeout(()=>setStage(i+1),t));},[]);
 useEffect(()=>{document.body.className=(light?'light ':'')+(recruiter?'recruiter':'')},[light,recruiter]);
 return <><div className="grid"/><header><a className="brand" href="#home"><b>YL</b><span>YASHWANTH.L</span></a><nav><a href="#about">About</a><a href="#projects">Systems</a><a href="#stack">Stack</a><a href="#journey">Journey</a></nav><div className="tools"><button onClick={()=>setRecruiter(!recruiter)}>{recruiter?'EXPERIENCE':'RECRUITER'} MODE</button><button className="icon" onClick={()=>setLight(!light)}>{light?<Sun/>:<Moon/>}</button></div></header>
 <main id="home">
 <section className={'intro s'+stage}>
   <div className="cinema"><div className="farLabel">INITIALIZING PROFILE / YASHWANTH.L</div><Avatar/><div className="walkline"><i/></div></div>
   <div className="profilePanel"><div className="eyebrow"><i/> DATA PROGRAMMER • JEDDAH, SAUDI ARABIA</div><h1>YASHWANTH<span>.L</span></h1><h2>DATA. AUTOMATION.<br/><em>SYSTEMS.</em></h2><p>I turn operational complexity into working digital systems — connecting data, business rules, automation, APIs and interfaces.</p><div className="facts"><div><small>EDUCATION</small><b>MCA</b><span>Academic profile: A+ presentation</span></div><div><small>CURRENT FOCUS</small><b>DATA PROGRAMMING</b><span>Automation & operational systems</span></div><div><small>STRENGTH</small><b>PROBLEM → SYSTEM</b><span>Understand • structure • automate</span></div><div><small>WORK</small><b>DAM UNITED</b><span>Jeddah, Saudi Arabia</span></div></div><div className="introBtns"><a href="#projects">EXPLORE MY SYSTEMS <ArrowDown/></a><a className="ghost" href="#about">ABOUT ME <ChevronRight/></a></div></div>
   <div className="gestureText">LET ME SHOW YOU<br/><b>WHAT I BUILD.</b></div>
 </section>
 <section id="about" className="section about"><div className="num">01 / PROFILE</div><div className="split"><h2>NOT JUST<br/>WORKING WITH DATA.<br/><em>BUILDING AROUND IT.</em></h2><div><p>I work where <strong>data, software and real operations</strong> meet. I look for repetitive processes, inconsistent information and business rules that should not depend on manual work.</p><p>Then I turn them into structured workflows — from Python and spreadsheet automation to web applications, APIs, validation systems, analytics and experimental document intelligence.</p><div className="logic">PROBLEM <i>→</i> DATA <i>→</i> LOGIC <i>→</i> AUTOMATION <i>→</i> RESULT</div></div></div></section>
 <section id="projects" className="section projects"><div className="num">02 / SYSTEMS I'VE BUILT</div><h2>REAL OPERATIONS.<br/><em>ENGINEERED WORKFLOWS.</em></h2><div className="cards">{projects.map((p,i)=><article key={p[0]}><div className="pno">PROJECT / {p[0]}</div><div className="visual">{i===0?<Workflow/>:i===1?<Database/>:i===2?<Code2/>:<ScanLine/>}<div className="scan"/></div><small>{p[2]}</small><h3>{p[1]}</h3><p>{p[4]}</p><div className="tags">{p[3]}</div></article>)}</div></section>
 <section id="stack" className="section stack"><div className="num">03 / TECH UNIVERSE</div><div className="split"><h2>TOOLS CHANGE.<br/><em>THE SYSTEM THINKING STAYS.</em></h2><p>I choose technology around the problem rather than forcing every problem into the same tool. My work crosses data processing, front-end interfaces, backend logic, automation and experimental vision workflows.</p></div><div className="orbit"><div className="core">YL<small>SYSTEMS</small></div>{skills.map((s,i)=><span key={s} style={{'--i':i}}>{s}</span>)}</div></section>
 <section id="journey" className="section journey"><div className="num">04 / EVOLUTION</div><h2>BUILT FROM<br/><em>OPERATIONS + TECHNOLOGY.</em></h2><div className="timeline"><div><b>01</b><small>FOUNDATION</small><h3>MCA</h3><p>Computer applications and technical foundation.</p></div><div><b>02</b><small>OPERATIONS</small><h3>HELP DESK</h3><p>Frontline problem solving and real operational support.</p></div><div><b>03</b><small>BUSINESS</small><h3>BUSINESS DEVELOPMENT</h3><p>Understanding requirements, people and outcomes.</p></div><div className="active"><b>04</b><small>NOW</small><h3>DATA PROGRAMMER</h3><p>Building automation, data workflows and operational systems.</p></div></div></section>
 <section className="final"><Terminal/><small>END OF DEMO.</small><h2>YOU'VE SEEN<br/>WHAT I BUILD.</h2><h3>NOW GIVE ME A <em>PROBLEM.</em></h3><p>Interested in data engineering, automation, internal platforms, operational technology and intelligent workflows.</p><a href="mailto:YOUR_EMAIL_HERE">INITIALIZE CONVERSATION <ExternalLink/></a><div className="links"><a href="YOUR_LINKEDIN_URL">LINKEDIN</a><a href="YOUR_GITHUB_URL">GITHUB</a></div></section>
 </main></>}
createRoot(document.getElementById('root')).render(<App/>);
